language: node_js
node_js:
  - "11"

cache:
  directories:
  - dapi-docs/node_modules
  - dapi-docs/vendor
  - provider/node_modules
  - widget/node_modules
  - login/node_modules
  - wallet/node_modules

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby-full
  - gem install bundler

script:
  - ./build.sh production

before_deploy:

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
