language: node_js
node_js:
  - "11"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install ruby-full
  - gem install bundler

script:
  - ./build.sh production

before_deploy:

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
